image:
  file: Dockerfile
tasks:
  - command: . .bashrc && echo Demo Bazel && ./run.sh
  - command: . .bashrc && gp open Dockerfile
  - command: . .bashrc && gp open .gitpod.yml
# - command: . .bashrc && echo Demo Scan-Build && cd ex-scan-build && ./run.sh
# - command: . .bashrc && echo Demo Checkout && git clone https://github.com/chromium/chromium
