# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:
- script: |
    sudo apt-get update
    sudo apt-get install -y pkg-config zip g++ zlib1g-dev unzip python3
    wget https://github.com/bazelbuild/bazel/releases/download/0.28.1/bazel-0.28.1-installer-linux-x86_64.sh
    sudo chmod +x bazel-0.28.1-installer-linux-x86_64.sh && ./bazel-0.28.1-installer-linux-x86_64.sh
    sudo apt-get install -y patch
    sudo apt-get install -y cmake
    sudo apt-get install -y ninja-build
    sudo apt-get install -y autoconf automake libtool
    bazel version
  displayName: 'Preparing environment ...'

- script: | 
    bazel build //source/common/network:utility_lib
  displayName: 'Building ...'

- script: |
    bazel build //test/common/network:utility_test
  displayName: 'Testing ...'
